# Static Vector config for the metrics DaemonSet.
# Mounted alongside the dynamic scrape config written by the sidecar helper.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-metrics-static
  namespace: kube-system
data:
  main.yaml: |
    data_dir: /var/lib/vector
  sinks.yaml: |
    sources:
      internal_metrics:
        type: internal_metrics
        scrape_interval_secs: 30

    transforms:
      tag_internal_metrics:
        type: remap
        inputs: ["internal_metrics"]
        source: |
          .tags.cluster = "${VECTOR_CLUSTER}"

    sinks:
      prometheus_remote_write:
        type: prometheus_remote_write
        inputs:
          - enrich_metrics
          - tag_internal_metrics
        endpoint: "https://nabu.sgl.com:9091/api/v1/push"
        healthcheck:
          enabled: false
